export const INDUSTRIES = [
  "Accounting",
  "Agriculture",
  "Airlines/Aviation",
  "Alternative Dispute Resolution",
  "Animation",
  "Apparel & Fashion",
  "Architecture & Planning",
  "Arts & Crafts",
  "Automotive",
  "Aviation & Aerospace",
  "Banking",
  "Biotechnology",
  "Broadcast Media",
  "Building Materials",
  "Business Supplies & Equipment",
  "Capital Markets",
  "Chemicals",
  "Civic & Social Organization",
  "Civil Engineering",
  "Commercial Real Estate",
  "Computer & Network Security",
  "Computer Games",
  "Computer Hardware",
  "Computer Networking",
  "Computer Software",
  "Construction",
  "Consumer Electronics",
  "Consumer Goods",
  "Consumer Services",
  "Cosmetics",
  "Dairy",
  "Defense & Space",
  "Design",
  "E-Learning",
  "Education Management",
  "Electrical/Electronic Manufacturing",
  "Entertainment",
  "Environmental Services",
  "Events Services",
  "Executive Office",
  "Facilities Services",
  "Farming",
  "Financial Services",
  "Fine Art",
  "Food & Beverages",
  "Food Production",
  "Fundraising",
  "Furniture",
  "Gambling & Casinos",
  "Glass, Ceramics & Concrete",
  "Government Administration",
  "Government Relations",
  "Graphic Design",
  "Health, Wellness & Fitness",
  "Higher Education",
  "Hospital & Health Care",
  "Hospitality",
  "Human Resources",
  "Import & Export",
  "Individual & Family Services",
  "Industrial Automation",
  "Information Services",
  "Information Technology & Services",
  "Insurance",
  "International Affairs",
  "International Trade & Development",
  "Internet",
  "Investment Banking",
  "Investment Management",
  "Judiciary",
  "Law Enforcement",
  "Law Practice",
  "Legal Services",
  "Legislative Office",
  "Leisure, Travel & Tourism",
  "Libraries",
  "Logistics & Supply Chain",
  "Luxury Goods & Jewelry",
  "Machinery",
  "Management Consulting",
  "Maritime",
  "Market Research",
  "Marketing & Advertising",
  "Mechanical or Industrial Engineering",
  "Media Production",
  "Medical Devices",
  "Medical Practice",
  "Mental Health Care",
  "Military",
  "Mining & Metals",
  "Motion Pictures & Film",
  "Museums & Institutions",
  "Music",
  "Nanotechnology",
  "Newspapers",
  "Non-Profit Organization Management",
  "Non-Profits & Non-Profit Services",
  "Oil & Energy",
  "Online Media",
  "Outsourcing/Offshoring",
  "Package/Freight Delivery",
  "Packaging & Containers",
  "Paper & Forest Products",
  "Performing Arts",
  "Pharmaceuticals",
  "Philanthropy",
  "Photography",
  "Plastics",
  "Political Organization",
  "Primary/Secondary Education",
  "Printing",
  "Professional Training & Coaching",
  "Program Development",
  "Public Policy",
  "Public Relations & Communications",
  "Public Safety",
  "Publishing",
  "Railroad Manufacture",
  "Ranching",
  "Real Estate",
  "Recreation & Sports",
  "Recreational Facilities & Services",
  "Religious Institutions",
  "Renewables & Environment",
  "Research",
  "Restaurants",
  "Retail",
  "Security & Investigations",
  "Semiconductors",
  "Shipbuilding",
  "Sporting Goods",
  "Sports",
  "Staffing & Recruiting",
  "Supermarkets",
  "Telecommunications",
  "Textiles",
  "Think Tanks",
  "Tobacco",
  "Translation & Localization",
  "Transportation/Trucking/Railroad",
  "Utilities",
  "Venture Capital & Private Equity",
  "Veterinary",
  "Warehousing",
  "Wholesale",
  "Wine & Spirits",
  "Wireless",
  "Writing & Editing",
] as const;

export const JOB_TITLES = [
  "Director",
  "Manager",
  "Founder",
  "General Manager",
  "Consultant",
  "Chief Executive Officer",
  "Co-Founder",
  "Account Manager",
  "Chief Financial Officer",
  "Human Resources Manager",
  "Director Of Marketing",
  "Executive Director",
  "Executive Assistant",
  "Administrative Assistant",
  "Director Of Human Resources",
  "Associate",
  "Chief Operating Officer",
  "HR Manager",
  "Account Executive",
  "Business Development Manager",
  "Director Of Operations",
  "Controller",
  "Chief Technology Officer",
  "Chief Information Officer",
  "Founder & CEO",
  "Attorney",
  "IT Manager",
  "Assistant Manager",
  "Engineer",
  "Business Analyst",
  "Accountant",
  "Chief Marketing Officer",
  "Creative Director",
  "Director Of Sales",
  "Graphic Designer",
  "Analyst",
  "Human Resources Director",
  "Founder And CEO",
  "Digital Marketing Manager",
  "Business Owner",
  "Branch Manager",
  "HR Director",
  "Administrator",
  "HR Business Partner",
  "Architect",
  "IT Director",
  "Finance Manager",
  "Director Of Business Development",
  "Developer",
  "Business Manager",
  "Director Of Engineering",
  "Engineering Manager",
  "CEO & Founder",
  "Director Of Finance",
  "Data Analyst",
  "Associate Director",
  "Accounting Manager",
  "Customer Service Manager",
  "IT Specialist",
  "Account Director",
  "Data Scientist",
  "District Manager",
  "Head Of Marketing",
  "Brand Manager",
  "Financial Controller",
  "Customer Success Manager",
  "IT Consultant",
  "HR Coordinator",
  "Chief Human Resources Officer",
  "Director Of Technology",
  "Business Development Executive",
  "HR Specialist",
  "Chief Operations Officer",
  "General Counsel",
  "Director Of Product Management",
  "Digital Marketing Specialist",
  "Chief Information Security Officer",
  "Communications Manager",
  "Construction Manager",
  "Director Of Communications",
  "Business Development Director",
  "Enterprise Architect",
  "Chief Revenue Officer",
  "Development Manager",
  "Chief Product Officer",
  "Director Of Digital Marketing",
  "Commercial Manager",
  "HR Consultant",
  "Logistics Manager",
  "Lead Software Engineer",
  "Director Of Recruiting",
  "Director Of Product Marketing",
  "Corporate Controller",
  "Director Of Talent Acquisition",
  "Commercial Director",
  "Chief People Officer",
  "Inside Sales Representative",
  "Devops Engineer",
  "Head Of Product",
  "Management Consultant",
  "Head Of HR",
  "Head Of Information Technology",
  "Head Of Operations",
  "Chief Strategy Officer",
  "Communications Director",
  "Content Marketing Manager",
  "Head Of Human Resources",
  "Email Marketing Manager",
  "Frontend Developer",
  "Client Services Manager",
  "IT Support Specialist",
  "Chief Medical Officer",
  "Director Of Product",
  "Country Manager",
  "Financial Consultant",
  "Field Marketing Manager",
  "Business Intelligence Analyst",
  "Inside Sales Manager",
  "Head Of Sales",
  "IT Recruiter",
  "Information Security Analyst",
  "Ecommerce Manager",
  "Chief Technical Officer",
  "Director Of Talent Acquisition",
  "Content Manager",
  "Business Development Specialist",
  "Compliance Officer",
  "Customer Service Specialist",
  "Compliance Manager",
  "Head Of IT",
  "IT Business Analyst",
  "Events Manager",
  "CEO & President",
  "Head Of Business Development",
  "Chief Administrative Officer",
  "Digital Marketing Director",
  "Digital Project Manager",
  "Chief Of Staff",
  "Chief Technology Officer (CTO)",
  "Digital Marketing Consultant",
  "Business Operations Manager",
  "Customer Experience Manager",
  "IT Operations Manager",
  "Enterprise Account Executive",
  "Learning And Development Manager",
  "Full Stack Developer",
  "Director Business Development",
  "Data Architect",
  "Design Manager",
  "Lead Consultant",
] as const;

export const COMPANY_SIZES = [
  "1-10",
  "11-20",
  "21-50",
  "51-100",
  "101-200",
  "201-500",
  "501-1000",
  "1001-2000",
  "2001-5000",
  "5001-10000",
  "10001+",
] as const;

export const EMAIL_STATUS_OPTIONS = [
  { label: "All", value: "all" },
  { label: "Verified", value: "verified" },
  { label: "Unverified", value: "unverified" },
] as const;

export const PIPELINE_STEPS = [
  { id: "scraping", label: "Scraping Leads", description: "Searching the database for matching leads..." },
  { id: "filtering", label: "Filtering LinkedIn", description: "Identifying leads with LinkedIn profiles..." },
  { id: "posts", label: "Fetching Posts", description: "Retrieving recent LinkedIn activity..." },
  { id: "emails", label: "Generating Emails", description: "Crafting personalized cold emails with AI..." },
] as const;

export const PRODUCT_COMPANY_SIZES = [
  "Unknown",
  "1-10",
  "11-50",
  "51-200",
  "201-500",
  "501-1000",
  "1001-5000",
  "5001-10000",
  "10001+",
] as const;

export const SALES_FUNNEL_TYPES = [
  "SaaS (Register → Trial → Paid)",
  "E-commerce",
  "Service-based",
  "Consulting",
  "Marketplace",
  "Freemium",
  "Enterprise Sales",
  "Direct Sales",
  "Partner/Channel Sales",
  "Custom",
] as const;

export const TIMEZONES = [
  "UTC",
  "America/New_York",
  "America/Chicago",
  "America/Denver",
  "America/Los_Angeles",
  "America/Toronto",
  "America/Sao_Paulo",
  "Europe/London",
  "Europe/Paris",
  "Europe/Berlin",
  "Europe/Madrid",
  "Europe/Rome",
  "Asia/Dubai",
  "Asia/Kolkata",
  "Asia/Singapore",
  "Asia/Tokyo",
  "Asia/Shanghai",
  "Asia/Hong_Kong",
  "Australia/Sydney",
  "Pacific/Auckland",
] as const;
